[build-system]
requires = ["flit_core>=3.12,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "sly"
description = "SLY - Sly Lex Yacc"
version = "0.6.0"
requires-python = ">=3.10"
readme = { file = "README.rst", content-type = "text/x-rst" }
license = "BSD-3-Clause"
license-files = ["LICENSE"]
authors = [{ name = "David Beazley", email = "dave@dabeaz.com" }]
maintainers = [{ name = "Sachaa-Thanasius", email = "sachaathanasius@gmail.com" }]
classifiers = [
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Typing :: Typed",
]

[project.urls]
Homepage = "https://github.com/Sachaa-Thanasius/sly/tree/modernization"
Documentation = "https://sly.readthedocs.io/en/latest/"

[dependency-groups]
test = ["pytest>=8"]
cov = ["coverage>=7", "covdefaults"]
profile = ["yelp-gprof2dot"]
dev = [
    "tox>=4.24.1",
    { include-group = "test" },
    { include-group = "cov" },
    { include-group = "profile" },
]


# -------- Test config --------

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib", "--strict-markers", "--strict-config"]
filterwarnings = ["error"]

[tool.coverage.run]
plugins = ["covdefaults"]
source = ["sly", "tests"]
omit = ["**/sly/ast.py", "**/sly/docparse.py", "**/sly/types.py"]
parallel = true

[tool.coverage.paths]
sly = ["src", "*/site-packages"]

[tool.coverage.report]
fail_under = 90
exclude_lines = ["^\\s*(?:el)?if TYPE_CHECKING:$"]


# -------- Linter config --------

[tool.ruff]
include = ["src/sly/*.py"]
line-length = 120

typing-modules = ["sly._typing_compat"]

[tool.ruff.lint]
select = [
    "A",
    "ANN",
    "ASYNC",
    "B",
    "BLE",
    "C4",
    "COM",
    "DTZ",
    "E",
    "EM",
    "ERA",
    "F",
    "FURB",
    "G",
    "I",
    "ICN",
    "INP",
    "ISC",
    "LOG",
    "NPY",
    "PD",
    "PERF",
    "PGH",
    "PIE",
    "PL",
    "PT",
    "PTH",
    "PYI",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SIM",
    "SLOT",
    "T10",
    "T20",
    "TC",
    "TID",
    "TRY",
    "UP",
    "W",
    "YTT",
    # "FBT",
]
extend-ignore = [
    # ---- General
    "S101",    # Use of assert here is a known quantity for typing cases. All uses should be safe to optimize out.
    "SIM105",  # Suppressable exception. contextlib.suppress is a stylistic choice with overhead.
    "C90",     # McCabe complexity.
    "ANN204",  # Special method return types are usually implicit and/or known by type checker.
    "ANN401",  # Any is needed for some annotations.
    "PT001",   # pytest recommends against empty parentheses on pytest.fixture.
    "TC001",   # Don't eagerly put things in TYPE_CHECKING blocks.
    "TC002",   # Don't eagerly put things in TYPE_CHECKING blocks.
    "TC003",   # Don't eagerly put things in TYPE_CHECKING blocks.
    "PD011",   # Erroneous issue that triggers for any .values attribute access at all.
    "PLR2004", # "Magic number" depends on the use case.
    "RUF002",  # "Ambiguous character" depends on the use case.
    "RUF003",  # "Ambiguous character" depends on the use case.
    "RUF022",  # __all__ ordering can be meaningful.
    "RUF023",  # __slots__ ordering can be meaningful. 

    # ---- Recommended by Ruff when using Ruff format
    "W191",
    "E111",
    "E114",
    "E117",
    "E501",
    "COM812",
    "COM819",
    "ISC001",
    "ISC002",
    "W291",   # Not recommended, but ruff format handles it as well.
    "W293",   # Not recommended, but ruff format handles it as well.

    # ---- Project-specific rules
    # Readability
    "SIM108", # if-else instead of a ternary.
    "RET505", # elif/else after return.
    "RET506", # elif/else after raise.
    "RET507", # elif/else after continue.
    "RET508", # elif/else after break.

    # Other
    "PLR",    # It's a parser generator; it's going to be complex.
    "ERA001", # Leave commented code alone.
    "RUF002", # Leave my en dashes alone.
    "PTH123", # Builtin open() is fine.
    "A005",   # Shadowing builtin modules is fine for sly submodules.
    "TC004",  # Intended usage of sly.types._ violates this.
]
unfixable = [
    "ERA", # Prevent unlikely erroneous deletion.
]

[tool.ruff.lint.isort]
lines-after-imports = 2
combine-as-imports = true

[tool.ruff.lint.pyupgrade]
keep-runtime-typing = true

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.per-file-ignores]
# ---- Library code
"**/__init__.py" = [
    # Ruff doesn't understand using star imports to export names in a package.
    "F403",
    "F405",
]
"src/sly/yacc.py" = [
    "E741", # Ambiguous names? No, math variable names.
]
"src/sly/_typing_compat.py" = [
    "PLW0603", # We update globals via global keyword to cache imported/created typing things.
]

# ---- Examples and test code
"tests/test_*.py" = [
    "RUF012", # Mutable class attributes.
    "F811",   # Redefining methods within Lexer/Parser subclasses is allowed because of metaclass hackery.
    "F821",   # Undefined names within Lexer/Parser subclasses are allowed because of metaclass hackery.
    "T201",   # Printing.
    "T203",   # Pretty-printing.
    "ANN001", # Annotations for parameters.
    "ANN201", # Annotations for public function returns.
    "ANN202", # Annotations for private function returns.
]
"examples/**/*.py" = [
    # Refer to explanations in the tests entry.
    "RUF012",
    "F811",
    "F821",
    "T201",
    "T203",
    "ANN001",
    "ANN201",
    "ANN202",
]


# -------- Type-checker config --------

[tool.pyright]
include = ["src/sly"]
ignore = ["examples/calc*", "examples/schcls.py", "tests"]
pythonVersion = "3.10"
pythonPlatform = "All"
typeCheckingMode = "strict"

defineConstant = { "TYPE_CHECKING" = true } # Just in case.

reportPrivateUsage = "none"                    # We're the library.
reportUnnecessaryIsInstance = "none"           # Verify user input.
reportUninitializedInstanceVariable = "none"   # Occasionally nice as a checkup, but otherwise noisy.
reportCallInDefaultInitializer = "warning"
reportImportCycles = "none"                    # Occasionally not a false positive.
reportPropertyTypeMismatch = "error"
reportShadowedImports = "error"
reportUnnecessaryTypeIgnoreComment = "warning"
reportMissingSuperCall = "none"
