[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sly"
description = "SLY - Sly Lex Yacc"
version = "0.6.0"
requires-python = ">=3.9"
readme = "README.rst"
license = "BSD-3-Clause"
authors = [{ name = "David Beazley", email = "dave@dabeaz.com" }]
maintainers = [
    { name = "Sachaa-Thanasius", email = "sachaathanasius@gmail.com" },
]
classifiers = [
    "License :: OSI Approved :: BSD License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Typing :: Typed",
]

[project.urls]
Homepage = "https://github.com/Sachaa-Thanasius/sly"
Documentation = "https://sly.readthedocs.io/en/latest/"

[tool.hatch.build.targets.wheel]
packages = ["src/sly"]


# ---- Test config

[[tool.hatch.envs.hatch-test.matrix]]
python = ["3.9", "3.10", "3.11", "3.12", "3.13"]

[tool.hatch.envs.hatch-test]
extra-dependencies = ["covdefaults"]

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib", "--strict-markers", "--strict-config"]

[tool.coverage.paths]
sly = ["src"]

[tool.coverage.run]
plugins = ["covdefaults"]
source = ["sly", "tests"]
omit = ["src/sly/ast.py", "src/sly/docparse.py", "src/sly/types.py"]

[tool.coverage.report]
fail_under = 90
exclude_lines = ["^\\s*(?:el)?if TYPE_CHECKING:$"]


# ---- Linter config

[tool.ruff]
include = ["src/sly/*.py"]
line-length = 120

[tool.ruff.lint]
typing-modules = ["sly._typing_compat"]

select = [
    "F",
    "E",
    "I",
    "UP",
    "YTT",
    "ANN",
    "ASYNC",
    "S",
    "BLE",
    # "FBT",
    "B",
    "A",
    "COM",
    "C4",
    "DTZ",
    "T10",
    "EM",
    "ISC",
    "G",
    "INP",
    "PIE",
    "T20",
    "PYI",
    "PT",
    "RSE",
    "RET",
    "SIM",
    "TID",
    "PTH",
    "ERA",
    "PL",
    "TRY",
    "PERF",
    "FURB",
    "RUF",
]
extend-ignore = [
    # ---- General
    "S101",    # Use of assert here is a known quantity for typing cases. All uses should be safe to optimize out.
    "SIM105",  # Suppressable exception. contextlib.suppress is a stylistic choice with overhead.
    "C90",     # McCabe complexity.
    "ANN204",  # Special method return types are usually implicit and/or known by type checker.
    "ANN401",  # Any is needed for some annotations.
    "UP038",   # isinstance performs better with tuples than unions.
    "PT001",   # pytest recommends against empty parentheses on pytest.fixture.
    "PD011",   # Erroneous issue that triggers for any .values attribute access at all.
    "PLR2004", # "Magic number" depends on the use case.
    "RUF002",  # "Ambiguous character" depends on the use case.
    "RUF003",  # "Ambiguous character" depends on the use case.
    "RUF022",  # __all__ ordering can be meaningful.
    "RUF023",  # __slots__ ordering can be meaningful. 

    # ---- Recommended by Ruff when using Ruff format
    "E111",
    "E114",
    "E117",
    "E501",
    "COM812",
    "COM819",
    "ISC001",
    "ISC002",

    # ---- Project-specific rules
    # Readability
    "RET505", # el(se|if) after return.
    "RET506", # el(se|if) after raise.
    "RET507", # el(se|if) after continue.
    "RET508", # el(se|if) after break.
    "SIM108", # if-else instead of a ternary.

    # Other
    "PLR",    # It's a parser generator; it's going to be complex.
    "ERA001", # Leave commented code alone.
    "RUF002", # Leave my en dashes alone.
    "PTH123", # Builtin open() is fine.
    "A005",   # Shadowing builtin modules is fine for sly submodules.
]
unfixable = [
    "ERA", # Prevent unlikely erroneous deletion.
]

[tool.ruff.lint.isort]
lines-after-imports = 2
combine-as-imports = true

[tool.ruff.lint.pyupgrade]
keep-runtime-typing = true

[tool.ruff.lint.per-file-ignores]
"src/sly/yacc.py" = [
    "E741", # Ambiguous names? No, math variable names.
]
"**/__init__.py" = [
    # Ruff doesn't understand using star imports to export names in a package.
    "F403",
    "F405",
]
"tests/test_*.py" = [
    "RUF012", # Mutable class attributes.
    "F811",   # Redefining methods within Lexer/Parser subclasses is allowed because of metaclass hackery.
    "F821",   # Undefined names within Lexer/Parser subclasses are allowed because of metaclass hackery.
    "T201",   # Printing.
    "T203",   # Pretty-printing.
    "ANN001", # Annotations for parameters.
    "ANN201", # Annotations for public function returns.
    "ANN202", # Annotations for private function returns.
]
"examples/**/*.py" = [
    # Refer to comments in the tests/*.py entry.
    "RUF012", # Mutable class attributes.
    "F811",
    "F821",
    "T201",   # Printing.
    "T203",   # Pretty-printing.
    "ANN001", # Annotations for parameters.
    "ANN201", # Annotations for public function returns.
    "ANN202", # Annotations for private function returns.
]


# ---- Type-checker config

[tool.pyright]
include = ["src/sly"]
ignore = ["examples/calc*", "examples/schcls.py", "tests"]
pythonVersion = "3.9"
pythonPlatform = "All"
typeCheckingMode = "strict"

defineConstant = { "TYPE_CHECKING" = true }

reportPrivateUsage = "none"                    # We're the library.
reportUnnecessaryIsInstance = "none"           # Verify user input.
reportUninitializedInstanceVariable = "none"   # Occasionally nice as a checkup, but otherwise noisy.
reportCallInDefaultInitializer = "warning"
reportImportCycles = "none"                    # Occasionally not a false positive.
reportPropertyTypeMismatch = "error"
reportShadowedImports = "error"
reportUnnecessaryTypeIgnoreComment = "warning"
