
requires = ["tox>=4.24.1"]
env_list = ["clean", "3.9", "3.10", "3.11", "3.12", "3.13", "coverage"]
skip_missing_interpreters = true

[env_run_base]
package = "wheel"
wheel_build_env = ".pkg"
dependency_groups = ["test", "cov"]
commands = [
    [
        "coverage",
        "run",
        "--debug=pathmap",
        "-m",
        "pytest",
        { replace = "posargs", extend = true },
    ],
]

[env.clean]
skip_install = true
dependency_groups = ["cov"]
commands = [["coverage", "erase"]]

[env.coverage]
skip_install = true
dependency_groups = ["cov"]
depends = ["3.9", "3.10", "3.11", "3.12", "3.13"]
commands = [["coverage", "combine"], ["coverage", "report"]]
